packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - core-js-pure
  - sharp
catalog:
  eslint: ^9.39.1
  react: ^19.2.0
  react-dom: ^19.2.0
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2
  "@types/node": ^24.10.0
  typescript: ^5.9.3
