packages:
  - apps/*
  - packages/*

catalog:
  "@types/node": ^25.6.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  eslint: ^10.2.1
  react: ^19.2.5
  react-dom: ^19.2.5
  typescript: ^6.0.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js-pure
  - sharp
