packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - core-js-pure
  - sharp
catalog:
  eslint: ^9.28.0
  react: ^19.1.1
  react-dom: ^19.1.1
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  typescript: ^5.9.2
