packages:
  - apps/*
  - packages/*

catalog:
  "@types/node": "25.9.3"
  "@types/react": "19.2.17"
  "@types/react-dom": "19.2.3"
  eslint: "9.39.2"
  react: "19.2.8"
  react-dom: "19.2.8"
  typescript: "6.0.3"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js-pure
  - sharp
