packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - core-js-pure
  - sharp
catalog:
  eslint: ^9.35.0
  react: ^19.1.1
  react-dom: ^19.1.1
  "@types/react": ^19.1.13
  "@types/react-dom": ^19.1.9
  "@types/node": ^24.5.2
  typescript: ^5.9.2
