name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: Setup AikidoSec/Safe-Chain
        run: |
          pnpm install -g @aikidosec/safe-chain@1.1.3
          safe-chain setup
      - run: pnpm install
      - run: pnpm run check
